version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq        # это как раз то, что используется вместо localhost
    ports:
      - 5672:5672   # AMQP port
      - 15672:15672 # Management UI port
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://127.0.0.1:15672"]
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 2
    networks:
      - app-network

  features:
    build:
      context: features
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  model:
    build:
      context: model
    depends_on:
      rabbitmq:
        condition: service_healthy
      features:
        condition: service_started
    networks:
      - app-network

  metric:
    build:
      context: metric
    depends_on:
      rabbitmq:
        condition: service_healthy
      features:
        condition: service_started
      model:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  plot:
    build:
      context: plot
    depends_on:
      rabbitmq:
        condition: service_healthy
      features:
        condition: service_started
      model:
        condition: service_started
      metric:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
  
#volumes:
#  logs_data:  # Определяем общий том для хранения логов

networks:
  app-network:
